In [2]:
# step 1: import libraries

import numpy as np
import pandas as pd

import re

from sklearn.model_selection  import train_test_split

from sklearn.preprocessing import LabelEncoder

from sklearn.feature_extraction.text import CountVectorizer

from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
# STEP 2: CREATE A SMALL BEGINNER DATASET
# ---------------------------------------------------------

# We are creating the dataset manually so it can run directly in Colab
# label = spam or ham
# message = the text message

data = {
    "label": [
        "ham", "spam", "ham", "spam", "ham", "spam", "ham", "spam", "ham", "spam",
        "ham", "spam", "ham", "spam", "ham", "spam", "ham", "spam", "ham", "spam"
    ],
    "message": [
        "Hey, are we meeting today?",
        "Congratulations! You won a free iPhone. Click now!",
        "Please send me the notes of today class",
        "Win cash prize now by clicking this link",
        "Can you call me after lunch?",
        "Limited offer! Buy now and get 50 percent discount",
        "I am on the way to college",
        "You have been selected for a free vacation",
        "Let's study together in the evening",
        "Claim your lottery reward today",
        "Can you help me with Python homework?",
        "Urgent! Your account has won a huge reward",
        "Where are you now?",
        "Free entry in contest, click here now",
        "I will reach home by 8 PM",
        "Get a free gift voucher instantly",
        "Did you complete the assignment?",
        "Exclusive deal only for you, act fast",
        "Let's go for tea after class",
        "You are a lucky winner, claim your prize"
    ]
}

# Convert dictionary into DataFrame
df = pd.DataFrame(data)

# Show first 5 rows
print("First 5 rows of dataset:")
print(df.head())

First 5 rows of dataset:
  label                                            message
0   ham                         Hey, are we meeting today?
1  spam  Congratulations! You won a free iPhone. Click ...
2   ham            Please send me the notes of today class
3  spam           Win cash prize now by clicking this link
4   ham                       Can you call me after lunch?


In [4]:
# STEP 3: CHECK DATASET INFORMATION
# ----------------------------------------------------

# Shape shows number of rows and columns
print("\nDataset shape:")
print(df.shape)

# Column names
print("\nColumn names:")
print(df.columns)

# Basic info
print("\nDataset info:")
df.info()

# Check missing values
print ("\nMissing values:")
print(df.isnull().sum())


Dataset shape:
(20, 2)

Column names:
Index(['label', 'message'], dtype='object')

Dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   label    20 non-null     object
 1   message  20 non-null     object
dtypes: object(2)
memory usage: 452.0+ bytes

Missing values:
label      0
message    0
dtype: int64


In [5]:

# STEP 4: TEXT CLEANING FUNCTION
# ---------------------------------------------------------

# This function will clean the text messages
# It does the following:
# 1. converts text to lowercase
# 2. removes numbers
# 3. removes punctuation/special characters
# 4. removes extra spaces

def clean_text(text):
    # convert to lowercase
    text = text.lower()

    # remove numbers
    text = re.sub(r'\d+', '', text)

    # remove special characters and punctuation
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# Apply cleaning function to message column
df["clean_message"] = df["message"].apply(clean_text)

print("\nDataset after text cleaning:")
print(df[["message", "clean_message"]].head())


Dataset after text cleaning:
                                             message  \
0                         Hey, are we meeting today?   
1  Congratulations! You won a free iPhone. Click ...   
2            Please send me the notes of today class   
3           Win cash prize now by clicking this link   
4                       Can you call me after lunch?   

                                     clean_message  
0                         hey are we meeting today  
1  congratulations you won a free iphone click now  
2          please send me the notes of today class  
3         win cash prize now by clicking this link  
4                      can you call me after lunch  


In [6]:
# STEP 5: LABEL ENCODING

# Machine learning model cannot understand text labels directly
# So we convert:
# ham  -> 0
# spam -> 1

label_encoder = LabelEncoder()
df["label_encoded"] = label_encoder.fit_transform(df["label"])

print("\nOriginal and encoded labels:")

print(df[["label", "label_encoded"]].head())

print("\nLabel mapping:")
for i, class_name in enumerate(label_encoder.classes_):
  print(f"{class_name} --> {i}")


Original and encoded labels:
  label  label_encoded
0   ham              0
1  spam              1
2   ham              0
3  spam              1
4   ham              0

Label mapping:
ham --> 0
spam --> 1


In [7]:
# STEP 6: SEPARATE FEATURES AND TARGET

# X = input feature (cleaned message text)
# y = target output (encoded label)

X = df["clean_message"]
y = df["label_encoded"]

print("\nFeature sample:")
print(X.head())

print("\nTarget sample:")
print(y.head())


Feature sample:
0                           hey are we meeting today
1    congratulations you won a free iphone click now
2            please send me the notes of today class
3           win cash prize now by clicking this link
4                        can you call me after lunch
Name: clean_message, dtype: object

Target sample:
0    0
1    1
2    0
3    1
4    0
Name: label_encoded, dtype: int64


In [8]:
# STEP 7: TRAIN-TEST SPLIT


# We split the data into:
# 80% training data
# 20% testing data

X_train, X_test, y_train, y_test = train_test_split(
    X,y, test_size=0.2, random_state=42
)

print("\nTrain-Test Split Shapes:")
print("X_train:", X_train.shape)
print("X-test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)


Train-Test Split Shapes:
X_train: (16,)
X-test: (4,)
y_train: (16,)
y_test: (4,)


In [9]:
# STEP 8: CONVERT TEXT INTO NUMBERS


# Machine learning models need numeric input
# CountVectorizer converts text into a bag-of-words numerical format

vectorizer = CountVectorizer()

X_train_vectorized = vectorizer.fit_transform(X_train)

X_test_vectorized = vectorizer.transform(X_test)

print("\nShape after vectorization:")
print("X_train_vectorized:", X_train_vectorized.shape)
print("X_test_vectorized:", X_test_vectorized.shape)

print("\nSample vocabulary words:")
print(list(vectorizer.vocabulary_.keys())[:10])


Shape after vectorization:
X_train_vectorized: (16, 74)
X_test_vectorized: (4, 74)

Sample vocabulary words:
['lets', 'study', 'together', 'in', 'the', 'evening', 'limited', 'offer', 'buy', 'now']


In [10]:
# STEP 9: TRAIN THE MODEL

# Multinomial Naive Bayes works very well for text classification

model = MultinomialNB()

# train the model using training data
model.fit(X_train_vectorized, y_train)

print("\nModel trained successfully!")


Model trained successfully!


In [11]:
# STEP 10: MAKE PREDICTIONS


# Predict on test data
y_pred = model.predict(X_test_vectorized)

print("\nPredicted values:")
print(y_pred)

print("\nActual values:")
print(y_test.values)


Predicted values:
[0 0 1 1]

Actual values:
[0 1 1 1]


In [12]:
# STEP 11: EVALUATE THE MODEL


# Accuracy tells how many predictions are correct
accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy of model:")
print(accuracy)

# classification report gives precision, recall, f1-score
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Confusion matrix shows correct and incorrect predictions
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Accuracy of model:
0.75

Classification Report:
              precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       1.00      0.67      0.80         3

    accuracy                           0.75         4
   macro avg       0.75      0.83      0.73         4
weighted avg       0.88      0.75      0.77         4


Confusion Matrix:
[[1 0]
 [1 2]]


In [13]:
# STEP 12: TEST WITH NEW CUSTOM MESSAGES


# Here we test our model on new messages written by us

new_messages =[
    "Congratulations you have won a free gift",
    "Can you send me the class link",
    "Claim your cash prize now",
    "I am coming in 10 minutes",
    "Exclusive offer only today buy now"
]

# clean the new messages
cleaned_new_messages = [clean_text(msg) for msg in new_messages]

#Convert them into numerical format
new_messages_vectorized = vectorizer.transform(cleaned_new_messages)

#predict spam or ham
new_predictions = model.predict(new_messages_vectorized)

print("\nNew Message Predictions:")
for msg, pred in zip(new_messages, new_predictions):
  label_name = label_encoder.inverse_transform([pred])[0]
  print(f"Message: {msg}")
  print(f"Prediction: {label_name}\n")
  print("-" * 50)


New Message Predictions:
Message: Congratulations you have won a free gift
Prediction: spam

--------------------------------------------------
Message: Can you send me the class link
Prediction: ham

--------------------------------------------------
Message: Claim your cash prize now
Prediction: spam

--------------------------------------------------
Message: I am coming in 10 minutes
Prediction: ham

--------------------------------------------------
Message: Exclusive offer only today buy now
Prediction: spam

--------------------------------------------------
